# Generated by Django 4.1 on 2022-08-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(default='', max_length=128, unique=True)),
                ('nickname', models.CharField(default='', max_length=128)),
                ('name', models.CharField(default='', max_length=128)),
                ('location_city', models.CharField(blank=True, default='null', max_length=64, null=True)),
                ('location_gu', models.CharField(blank=True, default='null', max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
