# Generated by Django 4.1 on 2022-08-19 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
                ('list_price', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('rental_fee', models.IntegerField()),
                ('explanation', models.TextField()),
                ('condition', models.IntegerField()),
                ('address', models.TextField()),
                ('detail_address', models.TextField()),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='product_photo')),
                ('barrow_available_start', models.DateField()),
                ('barrow_available_end', models.DateField()),
                ('barrow_method', models.CharField(max_length=256)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_barrowed', models.BooleanField(default=False)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_products', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myproducts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BarrowProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrow_start', models.DateField()),
                ('barrow_end', models.DateField()),
                ('is_return', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barrowed', to='BBApp.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myborrowproducts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
