# Generated by Django 4.1 on 2022-08-18 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BBApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='myproducts', to=settings.AUTH_USER_MODEL),
        ),
    ]
