# Generated by Django 4.1 on 2022-11-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBApp', '0003_alter_reviewresult_av_q1_alter_reviewresult_av_q2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='q1',
            new_name='q_1',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='q2',
            new_name='q_2',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='q3',
            new_name='q_3',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='q4',
            new_name='q_4',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='q5',
            new_name='q_5',
        ),
        migrations.AddField(
            model_name='barrowproduct',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
